name       : ripgrep-all
version    : 0.9.6
release    : 1
source     :
    - https://github.com/phiresky/ripgrep-all/archive/refs/tags/v0.9.6.tar.gz : 8cd7c5d13bd90ef0582168cd2bef73ca13ca6e0b1ecf24b9a5cd7cb886259023
homepage   : https://github.com/phiresky/ripgrep-all
license    : AGPL-3.0-or-later
component  : system.utils
summary    : ripgrep-all (rga) allows you to search PDFs, e-books, Office documents, archive formats and more
description: |
    rga is a line-oriented search tool that allows you to look for a regex in a multitude of file types. rga wraps the awesome ripgrep and enables it to search in pdf, docx, sqlite, jpg, movie subtitles (mkv, mp4), etc.
networking : yes
builddeps  :
    - cargo
rundeps    :
    - ripgrep
build      : |
    cargo build --release --locked
install    : |
    install -Dm00755 target/release/rga $installdir/usr/bin/rga
    install -Dm00755 target/release/rga-preproc $installdir/usr/bin/rga-preproc
check      : |
    cargo test --release --locked
